version: "3"
services:
  jenkins:
    build: .
    restart: always
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/jenkins_home/certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins: {}
