version: "3"
services:
  jenkins:
    image: 845151757650.dkr.ecr.us-east-1.amazonaws.com/jenkins_blueocean:2.426.2-jdk17      
    container_name: jenkins
    restart: always
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/jenkins_home/certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins: {}
